# Generated by Django 6.0.1 on 2026-02-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0013_alter_brand_options_brand_country_brand_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
    ]
