# Generated by Django 6.0.1 on 2026-02-08 15:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0016_order_is_paid_order_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='allow_backorder',
            field=models.BooleanField(default=False, verbose_name='Allow Backorder'),
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=50, verbose_name='Battery Capacity'),
        ),
        migrations.AddField(
            model_name='product',
            name='build_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Build Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='camera',
            field=models.TextField(blank=True, help_text='e.g., 50MP + 12MP + 12MP', verbose_name='Camera Setup'),
        ),
        migrations.AddField(
            model_name='product',
            name='charging_speed',
            field=models.CharField(blank=True, max_length=50, verbose_name='Charging Speed'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Comma separated list of colors', max_length=500, verbose_name='Available Colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price to show discount', max_digits=10, null=True, verbose_name='Compare/Original Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price for profit calculation', max_digits=10, null=True, verbose_name='Cost Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dimensions'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Display Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_type',
            field=models.CharField(blank=True, help_text='e.g., AMOLED, IPS LCD', max_length=100, verbose_name='Display Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='One feature per line', verbose_name='Key Features'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, max_length=100, verbose_name='Front Camera'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, verbose_name='Best Seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Mark as new product', verbose_name='New Arrival'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='Low Stock Threshold'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma separated keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='network',
            field=models.CharField(blank=True, help_text='e.g., 5G, 4G LTE', max_length=100, verbose_name='Network'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='Operating System'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Processor'),
        ),
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published At'),
        ),
        migrations.AddField(
            model_name='product',
            name='refresh_rate',
            field=models.CharField(blank=True, help_text='e.g., 120Hz, 90Hz', max_length=50, verbose_name='Refresh Rate'),
        ),
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, help_text='e.g., 2400x1080 pixels', max_length=100, verbose_name='Resolution'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(blank=True, default='7 Days Return Policy', max_length=200, verbose_name='Return Policy'),
        ),
        migrations.AddField(
            model_name='product',
            name='sim_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='SIM Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique product identifier', max_length=100, null=True, unique=True, verbose_name='Stock Keeping Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags for filtering', max_length=500, verbose_name='Product Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Reviews'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Sold'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_recording',
            field=models.CharField(blank=True, max_length=100, verbose_name='Video Recording'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='1 Year', max_length=100, verbose_name='Warranty Period'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_type',
            field=models.CharField(blank=True, help_text='e.g., Manufacturer, Seller', max_length=100, verbose_name='Warranty Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='whats_in_box',
            field=models.TextField(blank=True, help_text='List of items included', verbose_name="What's in the Box"),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Main Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Product is visible to customers', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured products section', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=50, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, max_length=50, verbose_name='Storage'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='myshop_prod_slug_a06e76_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='myshop_prod_categor_c4ccbe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='myshop_prod_brand_i_c82e07_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='myshop_prod_price_54c6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='myshop_prod_created_d56903_idx'),
        ),
    ]
